# Usage:
# eksctl create cluster -f eks.yaml
# eksctl delete cluster -f eks.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: skytest
  region: ap-northeast-2

managedNodeGroups:
  - name: large-cpu-nodes # Creates 1 16-CPU nodes
    instanceType: m5.4xlarge
    desiredCapacity: 1
